# Generated by Django 5.0 on 2023-12-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resized_file', models.FileField(upload_to='uploads/resized/')),
                ('thumbnail', models.FileField(upload_to='uploads/thumbnails/')),
                ('zip_file', models.FileField(upload_to='uploads/zips/')),
            ],
        ),
    ]
